# Lecture Week 4: Getting Data

## How to import a CSV file from a website

In [1]:
import pandas as pd
# Set the URL for the CDC mortality data CSV file
mortality_url = "https://data.cdc.gov/api/views/v6ab-adf5/rows.csv?accessType=DOWNLOAD"

# Use pandas to read the CSV file at the specified URL and create a DataFrame
mortality_data = pd.read_csv(mortality_url)

mortality_data.head()

   Year  Age Group  Death Rate
0  1900  1-4 Years      1983.8
1  1901  1-4 Years      1695.0
2  1902  1-4 Years      1655.7
3  1903  1-4 Years      1542.1
4  1904  1-4 Years      1591.5

## How to download a file to disk before importing it

In [3]:
import pandas as pd
from urllib import request

# Set the URL for the 2016 US presidential polls data CSV file
polls_url = "https://vincentarelbundock.github.io/Rdatasets/csv/dslabs/polls_us_election_2016.csv"
# download and save it with the specified filename
request.urlretrieve(polls_url, filename='./data/president_polls_2016.csv') # this name is arbitrary
polls = pd.read_csv('./data/president_polls_2016.csv')
polls.head(2)

,rownames,state,startdate,enddate,pollster,grade,samplesize,population,rawpoll_clinton,rawpoll_trump,rawpoll_johnson,rawpoll_mcmullin,adjpoll_clinton,adjpoll_trump,adjpoll_johnson,adjpoll_mcmullin
0,1,U.S.,2016-11-03,2016-11-06,ABC News/Washington Post,A+,2220.0,lv,47.00,43.00,4.00,NaN,45.20163,41.72430,4.626221,NaN
1,2,U.S.,2016-11-01,2016-11-07,Google Consumer Surveys,B,26574.0,lv,38.03,35.69,5.46,NaN,43.34557,41.21439,5.175792,NaN

What is the difference between using request.urlretrieve and simply giving a URL to the read_csv method?

This is an excellent question, and it's worth explaining to students because both approaches are valid but serve different purposes.

**Option 1: Read directly from a URL**
import pandas as pd

``` python
url = "https://example.com/data.csv"
df = pd.read_csv(url)
```


✅ One line of code

✅ Fast and convenient

❌ The file is not saved on your computer.

❌ You cannot inspect or reuse the downloaded file later.

**Option 2: Download first with urlretrieve()**

``` python
from urllib import request
import pandas as pd
url = "https://example.com/data.csv"
request.urlretrieve(url, "data.csv")
df = pd.read_csv("data.csv")
```
✅ The file is permanently stored on your computer.

✅ You can inspect it before reading.

✅ You can reuse it later without downloading again.

✅ Useful for ZIP files, Excel files, images, SQLite databases, PDFs, etc.

❌ Requires two steps.

urlretrieve() is a general download tool. It can download any file type, not just CSV files.

## How to work with a zip file on disk

### Download the zip file to disk

In [5]:
from urllib import request

url = "https://github.com/mwaskom/seaborn-data/archive/refs/heads/master.zip"

# Download the ZIP file
request.urlretrieve(url, "seaborn-data.zip") # saves in the current directory

('seaborn-data.zip', <http.client.HTTPMessage at 0x2245755d110>)

### Extract the files and list their names

In [7]:
# Import the ZipFile class from the zipfile module
from zipfile import ZipFile

# Create an empty list to store the names of extracted files
file_names = list() 

# Use the ZipFile class to open the zip file and extract its contents
with ZipFile('seaborn-data.zip', mode='r') as zip:
    zip.extractall('./data')
    # Iterate over each file in the zip file
    for file in zip.infolist():
        # Add the file's name to the list of file names
        file_names.append(file.filename)
        # Print the file's name, compressed size, and actual size
        print(file.filename, file.compress_size, file.file_size)

seaborn-data-master/ 0 0
seaborn-data-master/README.md 1135 3101
seaborn-data-master/anagrams.csv 146 361
seaborn-data-master/anscombe.csv 225 556
seaborn-data-master/attention.csv 310 1198
seaborn-data-master/brain_networks.csv 473353 1075911
seaborn-data-master/car_crashes.csv 1473 3301
seaborn-data-master/dataset_names.txt 120 174
seaborn-data-master/diamonds.csv 590452 2772143
seaborn-data-master/dots.csv 8211 25742
seaborn-data-master/dowjones.csv 3423 11349
seaborn-data-master/exercise.csv 541 2735
seaborn-data-master/flights.csv 695 2350
seaborn-data-master/fmri.csv 11745 38329
seaborn-data-master/geyser.csv 1044 4199
seaborn-data-master/glue.csv 460 2054
seaborn-data-master/healthexp.csv 2606 7222
seaborn-data-master/iris.csv 846 3858
seaborn-data-master/mpg.csv 6447 21222
seaborn-data-master/penguins.csv 2734 13478
seaborn-data-master/planets.csv 9646 36263
seaborn-data-master/png/ 0 0
seaborn-data-master/png/img1.png 607177 609809
seaborn-data-master/png/img2.png 499942 502606
seaborn-data-master/png/img3.png 596882 601434
seaborn-data-master/png/img4.png 693658 697425
seaborn-data-master/png/img5.png 535227 537883
seaborn-data-master/png/img6.png 532340 536030
seaborn-data-master/process/ 0 0
seaborn-data-master/process/attention.py 196 347
seaborn-data-master/process/dowjones.py 135 191
seaborn-data-master/process/exercise.py 217 385
seaborn-data-master/process/flights.py 394 1037
seaborn-data-master/process/gammas.py 455 882
seaborn-data-master/process/geyser.py 217 323
seaborn-data-master/process/glue.py 183 268
seaborn-data-master/process/healthexp.py 345 682
seaborn-data-master/process/mpg.py 174 264
seaborn-data-master/process/planets.py 201 316
seaborn-data-master/process/seaice.py 294 522
seaborn-data-master/process/taxis.py 564 1387
seaborn-data-master/process/titanic.py 482 881
seaborn-data-master/raw/ 0 0
seaborn-data-master/raw/attention.csv 146 361
seaborn-data-master/raw/dowjones.csv 3451 11566
seaborn-data-master/raw/exercise.csv 360 1112
seaborn-data-master/raw/geyser.csv 857 2275
seaborn-data-master/raw/glue.csv 353 689
seaborn-data-master/raw/healthexp.csv 13527 35139
seaborn-data-master/raw/mpg.csv 6203 17727
seaborn-data-master/raw/planets.csv 13098 47217
seaborn-data-master/raw/seaice.csv 34263 97883
seaborn-data-master/raw/taxi_zones.csv 2833 7675
seaborn-data-master/raw/taxis.csv 152458 687937
seaborn-data-master/raw/titanic.csv 19806 57726
seaborn-data-master/seaice.csv 62019 231046
seaborn-data-master/taxis.csv 160957 869349
seaborn-data-master/tips.csv 1770 9729
seaborn-data-master/titanic.csv 6802 57018

## How to read excel file in a zip file

In [9]:
from zipfile import ZipFile
import pandas as pd

# Path to the ZIP file
file_path = "./data/sample_data.zip"

# List to store file names
file_names = [] # list()

# Extract all files into the 'data' folder
with ZipFile(file_path, mode="r") as zip_ref:
    zip_ref.extractall()
    # Display information about the files in the ZIP archive
    print("\nFiles in the ZIP archive:")
    for file in zip_ref.infolist():
        file_names.append(file.filename)
        print(f"{file.filename} | Compressed: {file.compress_size} bytes | Original: {file.file_size} bytes")


# Read the Excel file from the extracted folder
df = pd.read_excel("./data/" + file_names[0], sheet_name=0) # , sheet_name=0 is the extracted file
print("\n")
df.head()

Files in the ZIP archive:
sales_data.xlsx | Compressed: 5053 bytes | Original: 5694 bytes
README.txt | Compressed: 32 bytes | Original: 30 bytes

   OrderID   Product     Category   Price  Quantity
0     1001    Laptop  Electronics  1200.0        15
1     1002     Mouse  Electronics    25.0       120
2     1003      Desk    Furniture   220.0        30
3     1004     Chair    Furniture    95.0        45
4     1005  Notebook   Stationery     4.5       300

## How to run queries against a database

In [11]:
# Import the sqlite3 module
import sqlite3

# Create a connection object to the DemoJobs.sqlite database
DemoJobs_con = sqlite3.connect('./data/DemoJobs.sqlite')

# Create a cursor object to execute SQL commands on the database
# cursor:  A database object that allows developers to traverse or retrieve rows one by one from a result set. 
# A cursor is a database object that acts as a pointer to the results of a SQL query.
DemoJobs_cur = DemoJobs_con.cursor()

# Use the cursor to execute an SQL command to retrieve the names of all tables in the database
DemoJobs_cur.execute('SELECT name, type FROM sqlite_master WHERE type="table"')

# Fetch all rows returned by the SQL command and print them
DemoJobs_cur.fetchall()

[('Companies', 'table'),
 ('Jobs', 'table'),
 ('Applicants', 'table'),
 ('Applications', 'table')]

## How to use a SQL query to import data into a DataFrame

### Get information about a table

In [13]:
# Execute a SQL PRAGMA command to retrieve information about the columns in the 'DemoJobs' table
# of the SQLite database connected to by 'DemoJobs_cur'
DemoJobs_cur.execute('PRAGMA table_info(Jobs)') # Applications, Jobs, Companies, Applicants

# Fetch all of the rows from the result set as a list of tuples
# Each tuple represents one column in the table, with values for the column ID, name, data type, etc.
result_set = DemoJobs_cur.fetchall()

# Print the result set
print(result_set)

[(0, 'JobID', 'INTEGER', 0, None, 1), (1, 'JobTitle', 'TEXT', 0, None, 0), (2, 'CompanyID', 'INTEGER', 0, None, 0), (3, 'EmploymentType', 'TEXT', 0, None, 0), (4, 'Salary', 'INTEGER', 0, None, 0), (5, 'PostedDate', 'TEXT', 0, None, 0)]

### Import the data from a query into a DataFrame

In [15]:
import pandas as pd
# Execute an SQL query to retrieve data from the 'Jobs' table of 
# the SQLite database connected to by 'DemoJobs_con'
# The SELECT statement retrieves specific columns from the table, 
query = '''
        SELECT JobID, JobTitle, Salary
        FROM Jobs
        '''

# Use the pd.read_sql_query() method to execute the query and store 
# the results in a Pandas DataFrame called 'DemoJobs'
# The method takes two arguments: the SQL query to execute, 
# and the database connection to use
DemoJobs = pd.read_sql_query(query, DemoJobs_con)
DemoJobs.head()

   JobID                JobTitle  Salary
0      1            Data Analyst   85000
1      2          Data Scientist  120000
2      3        Business Analyst   90000
3      4             ML Engineer  130000
4      5  Database Administrator   95000

## How to build DataFrames for the metadata and the data in a Stata file

### Get metadata from a Stata file

In [2]:
import pandas as pd
import pyreadstat
# Set the filename of the Stata file to be read in

stata_filename = 'data/auto.dta'

# Use the pyreadstat library to read in the metadata from the Stata file
df, meta = pyreadstat.read_dta(stata_filename, metadataonly=True) 
# metadataonly=True return empty df

# Print the type of the metadata object
print(type(meta))
df.head()

<class 'pyreadstat.pyclasses.metadata_container'>

Empty DataFrame
Columns: [make, price, mpg, rep78, headroom, trunk, weight, length, turn, displacement, gear_ratio, foreign]
Index: []

### What the attributes of the metadata container can tell you

In [10]:
print("Number of columns:", meta.number_columns)
print("Number of rows:", meta.number_rows)

Number of columns: 12
Number of rows: 74

In [12]:
print("column_labels:", meta.column_labels)
print("column_names:", meta.column_names)

column_labels: ['Make and model', 'Price', 'Mileage (mpg)', 'Repair record 1978', 'Headroom (in.)', 'Trunk space (cu. ft.)', 'Weight (lbs.)', 'Length (in.)', 'Turn circle (ft.)', 'Displacement (cu. in.)', 'Gear ratio', 'Car origin']
column_names: ['make', 'price', 'mpg', 'rep78', 'headroom', 'trunk', 'weight', 'length', 'turn', 'displacement', 'gear_ratio', 'foreign']

### How to build a DataFrame for the column descriptions in the metadata

In [21]:
import pandas as pd

meta_cols = pd.DataFrame(
    data = meta.column_labels, 
    # The data is the column_labels attribute from the meta object
    index = meta.column_names, 
    # The row index is the column_names attribute from the meta object
    columns=['description']  
    # The column name is 'description'
)

meta_cols.head()  # Display the first five rows of the resulting DataFrame

                 description
make          Make and model
price                  Price
mpg            Mileage (mpg)
rep78     Repair record 1978
headroom      Headroom (in.)

### How to import columns of the data into a DataFrame

In [ ]:
# Define the file path for the dataset
file_path = 'data/auto.dta'

# Specify the columns to be selected for the data frame
selected_columns = ['make',	'price', 'headroom', 'trunk']

# Read the Stata dataset with read_stata function and select only the specified columns
data = pd.read_stata(file_path, columns=selected_columns)

# Display the last 5 rows of the data frame
data.tail()

## How to download a JSON file

In [25]:
# import json module to work with JSON data
import json  
# import request module to retrieve data from URLs
from urllib import request  

# URL for the JSON data file
shots_url = 'https://www.murach.com/python_analysis/shots.json'  
# retrieve the data and save it to a file named 'shots.json'
request.urlretrieve(shots_url, filename='shots.json')

('shots.json', <http.client.HTTPMessage at 0x22457d4f350>)

## How to build a DataFrame for the data

In [27]:
# Open the 'shots.json' file using a context manager
# The file is opened in read-only mode and assigned to the variable 'json_data'
with open('shots.json') as json_data:
    # Load the contents of the JSON file into a dictionary called 'shots'
    shots = json.load(json_data)

# Extract the 'rowSet' from the 'resultSets' key in the 'shots' dictionary and assign it to 'allRows'
allRows = shots['resultSets'][0]['rowSet']

# Extract the column headers from the 'headers' key in the 'resultSets' key in the 'shots' dictionary
# Convert the column headers to lowercase using a list comprehension and assign them to 'columnHeaders'
columnHeaders = [x.lower() for x in shots['resultSets'][0]['headers']]

# Create a pandas DataFrame called 'shots' with 'allRows' as the data and 'columnHeaders' as the column names
shots = pd.DataFrame(data=allRows, columns=columnHeaders)

# Display the first few rows of the 'shots' DataFrame using the 'head()' method
shots.head()

,grid_type,game_id,game_event_id,player_id,player_name,team_id,team_name,period,minutes_remaining,seconds_remaining,...,shot_zone_area,shot_zone_range,shot_distance,loc_x,loc_y,shot_attempted_flag,shot_made_flag,game_date,htm,vtm
0,Shot Chart Detail,0020900015,4,201939,Stephen Curry,1610612744,Golden State Warriors,1,11,25,...,Right Side Center(RC),24+ ft.,26,99,249,1,0,20091028,GSW,HOU
1,Shot Chart Detail,0020900015,17,201939,Stephen Curry,1610612744,Golden State Warriors,1,9,31,...,Left Side Center(LC),16-24 ft.,18,-122,145,1,1,20091028,GSW,HOU
2,Shot Chart Detail,0020900015,53,201939,Stephen Curry,1610612744,Golden State Warriors,1,6,2,...,Center(C),8-16 ft.,14,-60,129,1,0,20091028,GSW,HOU
3,Shot Chart Detail,0020900015,141,201939,Stephen Curry,1610612744,Golden State Warriors,2,9,49,...,Left Side(L),16-24 ft.,19,-172,82,1,0,20091028,GSW,HOU
4,Shot Chart Detail,0020900015,249,201939,Stephen Curry,1610612744,Golden State Warriors,2,2,19,...,Left Side Center(LC),16-24 ft.,16,-68,148,1,0,20091028,GSW,HOU